FlatLimitPerChunk: 40
WandItem: STICK

incorrect_command: " /tapp"
command_claim_true: "§f You have claimed this property "
command_buy_true: "§f You have bought this property for "
command_buy_false: " Insufficient funds"
command_buy_nothing: " Nothing to buy"
command_sell_true: " You have set this property for sell"
command_sell_false: "Write a valid cost"
command_sell_nothing: " Nothing to sell"
command_delete_true: " You have deleted this property"
command_delete_nothing: " Nothing to delete"
command_info_nothing: " No property was found"
command_info_pos1: "Pos 1:"
command_info_pos2: "Pos 2:"
command_info_owner: "Owner:"
command_info_sell: "For sale: "
command_info_sell_button: "[SELL]"
command_info_roommates: "Roommates:"
command_info_roommates_button: " [REMOVE]"
command_limit_reached: "You have reached the limit for this chunk"
command_antispam: "Do not spam! Wait a bit"
command_list: "The list of properties:"
hologram_1: "§3FOR SALE"
hologram_4: "§6§LRight-Click to buy"
money_symbol: "$"

already_apartment_here: "There is already an apartment here"
clear_pos: " Your new position is on the other chunk.All selected positions have been cleared"